# Generated by Django 5.0.2 on 2024-02-10 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('start_date', models.DateField(verbose_name='Начало договора')),
                ('finish_date', models.DateField(verbose_name='Конец договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('contract_type', models.CharField(choices=[('EC', 'Договор энергетики'), ('HC', 'Договор отопления'), ('SC', 'Какой то договор')], max_length=100)),
                ('advertising_tax', models.BooleanField(default=False, verbose_name='Налог на рекламу')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт(Архив)')),
                ('at_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('invoice_num', models.CharField(max_length=50, verbose_name='Номер договора в счете')),
                ('basic_lot', models.IntegerField(blank=True, null=True, verbose_name='Основной лот')),
                ('basic_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_basic', to='add_tenant.contract', verbose_name='Основной договор')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to=settings.AUTH_USER_MODEL)),
                ('shopping_complex', models.ManyToManyField(to='add_tenant.shoppingcomplex')),
            ],
        ),
    ]
