# Generated by Django 5.0.2 on 2024-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='basic_contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='basic_contract',
            field=models.ManyToManyField(blank=True, related_name='contract_basic', to='add_tenant.contract', verbose_name='Основной договор'),
        ),
    ]
